### ISSUE TITLE
Why reverse history clicked news？

### ISSUE THREAD

**Issue by nipirennipi** [resistzzz/Prompt4NR#4]
`prepro_data.py:line42`
`his_clicks.reverse()`

**Comment by resistzzz** [comment]
Because a user's history generally too long, but the BERT can be inputted only 512 tokens. After you concatenate the <USER> sentence, you need to make a trunction. 
Of course, I want to reserve the latest clicked news, so making such "reverse()" operation is convenient for me to reserve the lastest clicked news in the <USER> sentence. I just need to set a threshold and cut off the these tokens that surpass the threshold length, and the previous tokens are the latest user's clicked news I want to obtain.

**Comment by nipirennipi** [comment]
@resistzzz got it
